// @ts-check
const expoConfig = require("eslint-config-expo/flat");
const prettierConfig = require("eslint-config-prettier");

module.exports = [
  ...expoConfig,
  prettierConfig,
  {
    // Generated by openapi-typescript (AC-6.1/AC-6.7) — never hand-edited, never linted.
    ignores: ["api/**", ".expo/**", "node_modules/**"],
  },
  {
    rules: {
      // R-5 / AC-2.5: no raw hex literals in component/screen code — tokens come from
      // frontend/theme/ only. openapi generation output and config files are exempt via
      // the ignores block above / overrides below.
      "no-restricted-syntax": [
        "error",
        {
          selector: "Literal[value=/^#[0-9a-fA-F]{3,8}$/]",
          message:
            "No raw hex colors in components/screens — use a token from frontend/theme/ (AC-2.5, frontend/README.md).",
        },
      ],
    },
  },
  {
    files: [
      "theme/**/*.ts",
      "theme/**/*.tsx",
      "app.config.ts",
      "jest.config.js",
      "jest.setup.js",
      "__tests__/**/*.ts",
      "__tests__/**/*.tsx",
    ],
    rules: {
      // Token definitions themselves are the one legitimate place raw hex values exist — they ARE
      // the transcription from docs/design/canvas/ (AC-2.2). Tests need the same exemption to
      // assert against a token's literal value (AC-10.4).
      "no-restricted-syntax": "off",
    },
  },
];
