<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Concert domain (docs/specs/2026-08-21-concert-domain-api.md): `bands`, `concert_bands`,
 * `concerts`. `bands.normalized_name` carries the dedup unique index (D-25, AC-8.2);
 * `concert_bands` carries the two lineup-shape constraints (AC-1.3, AC-1.6); `concerts` carries the
 * two `(owner_id, ...)` composite indexes `App\State\Provider\ConcertCollectionProvider` and
 * `App\Filter\ConcertStatusFilter` rely on to keep the status/date filters index-backed (D-24,
 * AC-3.7) without a per-row timezone computation at query time.
 */
final class Version20260821150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Concert domain: bands, concert_bands, concerts.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bands (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, normalized_name VARCHAR(120) NOT NULL, setlistfm_mbid VARCHAR(64) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_bands_setlistfm_mbid ON bands (setlistfm_mbid)');
        $this->addSql('CREATE UNIQUE INDEX uniq_bands_normalized_name ON bands (normalized_name)');
        $this->addSql('CREATE TABLE concert_bands (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, billing_order SMALLINT NOT NULL, concert_id INT NOT NULL, band_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_293BC17E83C97B2E ON concert_bands (concert_id)');
        $this->addSql('CREATE INDEX IDX_293BC17E49ABEB17 ON concert_bands (band_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_concert_bands_concert_band ON concert_bands (concert_id, band_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_concert_bands_concert_billing ON concert_bands (concert_id, billing_order)');
        $this->addSql('CREATE TABLE concerts (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, timezone VARCHAR(64) NOT NULL, past_after TIMESTAMP(0) WITH TIME ZONE NOT NULL, price_amount INT DEFAULT NULL, price_currency VARCHAR(3) DEFAULT NULL, doors_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, start_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, venue_name VARCHAR(200) DEFAULT NULL, venue_city VARCHAR(200) DEFAULT NULL, venue_country_code VARCHAR(2) DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_730600F17E3C61F9 ON concerts (owner_id)');
        $this->addSql('CREATE INDEX idx_concerts_owner_past_after ON concerts (owner_id, past_after)');
        $this->addSql('CREATE INDEX idx_concerts_owner_date ON concerts (owner_id, date)');
        $this->addSql('ALTER TABLE concert_bands ADD CONSTRAINT FK_293BC17E83C97B2E FOREIGN KEY (concert_id) REFERENCES concerts (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE concert_bands ADD CONSTRAINT FK_293BC17E49ABEB17 FOREIGN KEY (band_id) REFERENCES bands (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE concerts ADD CONSTRAINT FK_730600F17E3C61F9 FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE concert_bands DROP CONSTRAINT FK_293BC17E83C97B2E');
        $this->addSql('ALTER TABLE concert_bands DROP CONSTRAINT FK_293BC17E49ABEB17');
        $this->addSql('ALTER TABLE concerts DROP CONSTRAINT FK_730600F17E3C61F9');
        $this->addSql('DROP TABLE bands');
        $this->addSql('DROP TABLE concert_bands');
        $this->addSql('DROP TABLE concerts');
    }
}
