<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Playlist fast-mode backend (docs/specs/2026-08-23-playlist-fast-mode-backend.md, D-145-D-160):
 * `track_resolutions`, `playlist_generation_jobs`, `playlists`, `playlist_tracks` — FK order. Two
 * partial unique indexes are hand-added as raw SQL because Doctrine's `#[ORM\UniqueConstraint]`
 * cannot express a `WHERE` clause (D-146's identity note: all four tables use the project's
 * standard integer surrogate key, generated with `doctrine:migrations:diff` and hand-edited only for
 * these two indexes — the ORM diff otherwise matched the entity mapping exactly).
 */
final class Version20260823000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Playlist fast-mode backend: track_resolutions, playlist_generation_jobs, playlists, playlist_tracks (D-145-D-160).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE track_resolutions (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                provider VARCHAR(32) NOT NULL,
                algorithm_version SMALLINT NOT NULL,
                normalized_title VARCHAR(200) NOT NULL,
                normalized_artist VARCHAR(200) NOT NULL,
                provider_track_id VARCHAR(128) DEFAULT NULL,
                confidence DOUBLE PRECISION NOT NULL,
                outcome VARCHAR(32) NOT NULL,
                candidates_digest JSON NOT NULL,
                resolved_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                expires_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_track_resolution ON track_resolutions (provider, algorithm_version, normalized_artist, normalized_title)');
        $this->addSql('CREATE INDEX idx_track_resolutions_expires ON track_resolutions (expires_at)');

        $this->addSql(<<<'SQL'
            CREATE TABLE playlist_generation_jobs (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                owner_id INT NOT NULL,
                concert_id INT NOT NULL,
                provider_key VARCHAR(32) NOT NULL,
                streaming_account_id INT NOT NULL,
                mode VARCHAR(16) NOT NULL,
                state VARCHAR(32) NOT NULL,
                idempotency_key VARCHAR(64) NOT NULL,
                attempt SMALLINT NOT NULL,
                algorithm_version SMALLINT NOT NULL,
                candidate_setlists JSON DEFAULT NULL,
                selected_setlists JSON DEFAULT NULL,
                pending_choices JSON DEFAULT NULL,
                user_choices JSON DEFAULT NULL,
                songs_total INT NOT NULL,
                songs_processed INT NOT NULL,
                current_stage VARCHAR(24) DEFAULT NULL,
                stage_entered_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                blocked_reason VARCHAR(32) DEFAULT NULL,
                resumable_after TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                blocked_at_stage VARCHAR(24) DEFAULT NULL,
                block_cycle_count SMALLINT NOT NULL,
                blocked_ms INT NOT NULL,
                failure_reason VARCHAR(32) DEFAULT NULL,
                failure_detail JSON DEFAULT NULL,
                result_kind VARCHAR(24) DEFAULT NULL,
                matched_count INT NOT NULL,
                low_confidence_count INT NOT NULL,
                not_found_count INT NOT NULL,
                skipped_count INT NOT NULL,
                region_restricted_count INT NOT NULL,
                mean_confidence DOUBLE PRECISION DEFAULT NULL,
                duration_ms INT DEFAULT NULL,
                stage_timings JSON DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                started_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                finished_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                suspended_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                expires_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_pgj_owner ON playlist_generation_jobs (owner_id)');
        $this->addSql('CREATE INDEX idx_pgj_concert ON playlist_generation_jobs (concert_id)');
        $this->addSql('CREATE INDEX idx_pgj_streaming_account ON playlist_generation_jobs (streaming_account_id)');
        $this->addSql('CREATE INDEX idx_pgj_state_resumable ON playlist_generation_jobs (state, resumable_after)');
        $this->addSql('CREATE INDEX idx_pgj_state_expires ON playlist_generation_jobs (state, expires_at)');
        $this->addSql('CREATE INDEX idx_pgj_owner_concert ON playlist_generation_jobs (owner_id, concert_id)');
        $this->addSql('CREATE INDEX idx_pgj_created_at ON playlist_generation_jobs (created_at)');
        // D-129 — level-1 idempotency: a double-tapped start collides on the database, not a service check.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_live_generation
              ON playlist_generation_jobs (concert_id, provider_key)
              WHERE state IN ('queued','resolving_setlist','awaiting_setlist_choice',
                              'matching','awaiting_version_choice','building','blocked')
            SQL);
        // D-144 — anti-starvation floor. Deliberately excludes blocked/awaiting_* so a job waiting on
        // tomorrow's quota does not stop the same user starting a different generation.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_live_generation_per_user
              ON playlist_generation_jobs (owner_id)
              WHERE state IN ('queued','resolving_setlist','matching','building')
            SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE playlist_generation_jobs
              ADD CONSTRAINT fk_pgj_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE playlist_generation_jobs
              ADD CONSTRAINT fk_pgj_concert FOREIGN KEY (concert_id) REFERENCES concerts (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE playlist_generation_jobs
              ADD CONSTRAINT fk_pgj_streaming_account FOREIGN KEY (streaming_account_id) REFERENCES streaming_accounts (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE playlists (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                owner_id INT NOT NULL,
                concert_id INT NOT NULL,
                job_id INT NOT NULL,
                provider_key VARCHAR(32) NOT NULL,
                provider_playlist_id VARCHAR(128) DEFAULT NULL,
                creation_attempted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                external_url TEXT DEFAULT NULL,
                name VARCHAR(200) NOT NULL,
                description TEXT DEFAULT NULL,
                inserted_through_ordinal INT NOT NULL,
                report_summary JSON NOT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE INDEX idx_playlists_owner ON playlists (owner_id)');
        $this->addSql('CREATE INDEX idx_playlists_concert ON playlists (concert_id)');
        $this->addSql('CREATE INDEX idx_playlists_owner_concert ON playlists (owner_id, concert_id)');
        $this->addSql('CREATE INDEX idx_playlists_job ON playlists (job_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE playlists
              ADD CONSTRAINT fk_playlists_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE playlists
              ADD CONSTRAINT fk_playlists_concert FOREIGN KEY (concert_id) REFERENCES concerts (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE playlists
              ADD CONSTRAINT fk_playlists_job FOREIGN KEY (job_id) REFERENCES playlist_generation_jobs (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE playlist_tracks (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                playlist_id INT NOT NULL,
                ordinal INT NOT NULL,
                source_song_id INT DEFAULT NULL,
                source_band_id INT NOT NULL,
                source_setlistfm_id VARCHAR(64) NOT NULL,
                source_position INT NOT NULL,
                source_title VARCHAR(200) NOT NULL,
                segment_index SMALLINT DEFAULT NULL,
                provider_track_id VARCHAR(128) DEFAULT NULL,
                confidence DOUBLE PRECISION DEFAULT NULL,
                outcome VARCHAR(32) NOT NULL,
                reason_code VARCHAR(48) DEFAULT NULL,
                reason_params JSON DEFAULT NULL,
                inserted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_playlist_track_ordinal ON playlist_tracks (playlist_id, ordinal)');
        $this->addSql('CREATE INDEX idx_playlist_tracks_source ON playlist_tracks (playlist_id, source_position)');
        $this->addSql('CREATE INDEX idx_playlist_tracks_song ON playlist_tracks (source_song_id)');
        $this->addSql('CREATE INDEX idx_playlist_tracks_band ON playlist_tracks (source_band_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE playlist_tracks
              ADD CONSTRAINT fk_pt_playlist FOREIGN KEY (playlist_id) REFERENCES playlists (id) ON DELETE CASCADE NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE playlist_tracks
              ADD CONSTRAINT fk_pt_source_song FOREIGN KEY (source_song_id) REFERENCES songs (id) ON DELETE SET NULL NOT DEFERRABLE
            SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE playlist_tracks
              ADD CONSTRAINT fk_pt_source_band FOREIGN KEY (source_band_id) REFERENCES bands (id) NOT DEFERRABLE
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE playlist_tracks DROP CONSTRAINT fk_pt_playlist');
        $this->addSql('ALTER TABLE playlist_tracks DROP CONSTRAINT fk_pt_source_song');
        $this->addSql('ALTER TABLE playlist_tracks DROP CONSTRAINT fk_pt_source_band');
        $this->addSql('DROP TABLE playlist_tracks');

        $this->addSql('ALTER TABLE playlists DROP CONSTRAINT fk_playlists_owner');
        $this->addSql('ALTER TABLE playlists DROP CONSTRAINT fk_playlists_concert');
        $this->addSql('ALTER TABLE playlists DROP CONSTRAINT fk_playlists_job');
        $this->addSql('DROP TABLE playlists');

        $this->addSql('ALTER TABLE playlist_generation_jobs DROP CONSTRAINT fk_pgj_owner');
        $this->addSql('ALTER TABLE playlist_generation_jobs DROP CONSTRAINT fk_pgj_concert');
        $this->addSql('ALTER TABLE playlist_generation_jobs DROP CONSTRAINT fk_pgj_streaming_account');
        $this->addSql('DROP TABLE playlist_generation_jobs');

        $this->addSql('DROP TABLE track_resolutions');
    }
}
