<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Notes and reviews (docs/specs/2026-08-26-notes-and-reviews.md, D-227-D-247): promotes
 * `Concert.note` into its own `concert_reviews` table.
 *
 * Copy → verify → drop, all in one transaction (D-239, AC-8.5): every `Concert` whose `note` is
 * non-null and non-blank after trimming becomes a notes-only `ConcertReview` (`rating` NULL,
 * `source_note_migrated_at` = now(), AC-8.1/AC-8.2), a `DO` block aborts the whole migration if the
 * inserted count does not match the source count (R-1), and only then is `concerts.note` dropped.
 * `down()` re-adds the column and restores exactly the rows this migration created (identified by
 * `source_note_migrated_at IS NOT NULL`) before dropping the table (D-239).
 */
final class Version20260826140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Notes and reviews: concert_reviews table, migrate Concert.note into it, drop Concert.note.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE concert_reviews (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                owner_id INT NOT NULL,
                concert_id INT NOT NULL,
                rating SMALLINT DEFAULT NULL,
                notes TEXT DEFAULT NULL,
                highlight_song_id INT DEFAULT NULL,
                highlight_title VARCHAR(200) DEFAULT NULL,
                source_note_migrated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_concert_reviews_owner_concert ON concert_reviews (owner_id, concert_id)');
        $this->addSql('CREATE INDEX idx_concert_reviews_concert ON concert_reviews (concert_id)');
        $this->addSql('CREATE INDEX idx_concert_reviews_highlight_song ON concert_reviews (highlight_song_id)');
        $this->addSql('ALTER TABLE concert_reviews ADD CONSTRAINT FK_concert_reviews_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE concert_reviews ADD CONSTRAINT FK_concert_reviews_concert FOREIGN KEY (concert_id) REFERENCES concerts (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE concert_reviews ADD CONSTRAINT FK_concert_reviews_highlight_song FOREIGN KEY (highlight_song_id) REFERENCES songs (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE concert_reviews ADD CONSTRAINT chk_concert_reviews_rating CHECK (rating IS NULL OR rating BETWEEN 1 AND 5)');

        // AC-8.1, AC-8.2: verbatim copy, no trim/normalize/re-encode — the trim below only decides
        // *whether* a note migrates, never *what* is migrated.
        $this->addSql(<<<'SQL'
            INSERT INTO concert_reviews (owner_id, concert_id, notes, rating, created_at, updated_at, source_note_migrated_at)
            SELECT c.owner_id, c.id, c.note, NULL, c.updated_at, c.updated_at, NOW()
            FROM concerts c
            WHERE c.note IS NOT NULL AND btrim(c.note) <> ''
            SQL);

        // R-1/AC-8.5: abort the whole transaction (including the DROP COLUMN below) if the migrated
        // count does not match the source count — "the migration ran" is not "the data arrived".
        $this->addSql(<<<'SQL'
            DO $$
            DECLARE
                expected_count INT;
                actual_count INT;
            BEGIN
                SELECT COUNT(*) INTO expected_count FROM concerts WHERE note IS NOT NULL AND btrim(note) <> '';
                SELECT COUNT(*) INTO actual_count FROM concert_reviews WHERE source_note_migrated_at IS NOT NULL;
                IF expected_count <> actual_count THEN
                    RAISE EXCEPTION 'concerts.note migration count mismatch: expected %, got %', expected_count, actual_count;
                END IF;
            END
            $$
            SQL);

        $this->addSql('ALTER TABLE concerts DROP COLUMN note');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE concerts ADD note TEXT DEFAULT NULL');

        // Restore exactly the rows this migration created — identified by source_note_migrated_at,
        // never by "every concert_reviews row with no rating" (D-240).
        $this->addSql(<<<'SQL'
            UPDATE concerts c
            SET note = cr.notes
            FROM concert_reviews cr
            WHERE cr.concert_id = c.id AND cr.source_note_migrated_at IS NOT NULL
            SQL);

        $this->addSql('DROP TABLE concert_reviews');
    }
}
