<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Backoffice provider configuration (docs/specs/2026-08-22-backoffice-provider-configuration.md,
 * D-89–D-105): `provider_settings` — behaviour flags only, no credential column, ever (AC-9.1). A
 * partial unique index enforces at most one default at the storage layer (AC-7.1). Seeds `spotify`
 * (enabled, embed, default — today's actual, unmonetized behaviour) and `youtube` (disabled, off,
 * not default — the row exists so prompt 18 is a flag flip, not a migration; D-99's adapter-
 * intersection rule keeps it invisible from the public endpoint until an adapter exists) (D-102).
 */
final class Version20260822150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Backoffice provider configuration: provider_settings, seeded spotify/youtube (D-89-D-105).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE provider_settings (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                provider VARCHAR(32) NOT NULL,
                enabled BOOLEAN NOT NULL,
                playback_mode VARCHAR(20) NOT NULL,
                is_default BOOLEAN NOT NULL,
                notes TEXT DEFAULT NULL,
                created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_provider_settings_provider ON provider_settings (provider)');
        // AC-2.1: playbackMode's enum is also enforced at the database level, not just by the ORM.
        $this->addSql("ALTER TABLE provider_settings ADD CONSTRAINT chk_provider_settings_playback_mode CHECK (playback_mode IN ('embed', 'deeplink', 'off'))");
        // AC-7.1: at most one default, survives a manual psql write — not just an application-level guard.
        $this->addSql('CREATE UNIQUE INDEX uniq_provider_settings_is_default ON provider_settings (is_default) WHERE is_default');

        // D-102: spotify — the current, working, unmonetized state. youtube — disabled/off/not-default
        // so its row exists for prompt 18 without a migration, but D-99 keeps it invisible until an
        // adapter is registered. apple is not seeded — not on the roadmap.
        $this->addSql(<<<'SQL'
            INSERT INTO provider_settings (provider, enabled, playback_mode, is_default, notes, created_at, updated_at)
            VALUES ('spotify', true, 'embed', true, NULL, NOW(), NOW())
            SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO provider_settings (provider, enabled, playback_mode, is_default, notes, created_at, updated_at)
            VALUES ('youtube', false, 'off', false, NULL, NOW(), NOW())
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE provider_settings');
    }
}
