<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260821164001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Backoffice foundation: append-only audit_log_entries table (D-43, AC-12.1).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audit_log_entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_id INT NOT NULL, actor_label VARCHAR(32) NOT NULL, action VARCHAR(64) NOT NULL, subject_type VARCHAR(64) NOT NULL, subject_id VARCHAR(64) NOT NULL, field VARCHAR(64) DEFAULT NULL, old_value TEXT DEFAULT NULL, new_value TEXT DEFAULT NULL, ip_address VARCHAR(45) NOT NULL, user_agent VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_log_entries_occurred_at ON audit_log_entries (occurred_at)');
        $this->addSql('CREATE INDEX idx_audit_log_entries_subject ON audit_log_entries (subject_type, subject_id)');
        $this->addSql('CREATE INDEX idx_audit_log_entries_action ON audit_log_entries (action)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE audit_log_entries');
    }
}
