<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Playlist normal mode (docs/specs/2026-08-25-playlist-normal-mode.md, D-188-D-209):
 * `user_track_preferences` (D-198), plus three nullable columns on `playlist_generation_jobs`
 * (`choices_required_count`, `choices_made_count`, `resumed_from_job_id`, D-209/AC-9.1/AC-4.3). No
 * migration for `candidate_setlists`/`pending_choices`/`user_choices` — those jsonb columns already
 * exist from spec 14.
 */
final class Version20260825120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Playlist normal mode: user_track_preferences table, decision-count and resumed-from-job columns on playlist_generation_jobs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE user_track_preferences (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                owner_id INT NOT NULL,
                provider VARCHAR(32) NOT NULL,
                algorithm_version SMALLINT NOT NULL,
                normalized_artist VARCHAR(200) NOT NULL,
                normalized_title VARCHAR(200) NOT NULL,
                provider_track_id VARCHAR(128) NOT NULL,
                chosen_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                used_count INT NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_user_track_preference ON user_track_preferences (owner_id, provider, algorithm_version, normalized_artist, normalized_title)');
        $this->addSql('CREATE INDEX idx_user_track_preferences_owner ON user_track_preferences (owner_id)');
        $this->addSql('ALTER TABLE user_track_preferences ADD CONSTRAINT FK_user_track_preferences_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('ALTER TABLE playlist_generation_jobs ADD choices_required_count INT DEFAULT NULL');
        $this->addSql('ALTER TABLE playlist_generation_jobs ADD choices_made_count INT DEFAULT NULL');
        $this->addSql('ALTER TABLE playlist_generation_jobs ADD resumed_from_job_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE playlist_generation_jobs ADD CONSTRAINT FK_pgj_resumed_from_job FOREIGN KEY (resumed_from_job_id) REFERENCES playlist_generation_jobs (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_pgj_resumed_from_job ON playlist_generation_jobs (resumed_from_job_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE playlist_generation_jobs DROP CONSTRAINT FK_pgj_resumed_from_job');
        $this->addSql('DROP INDEX idx_pgj_resumed_from_job');
        $this->addSql('ALTER TABLE playlist_generation_jobs DROP choices_required_count');
        $this->addSql('ALTER TABLE playlist_generation_jobs DROP choices_made_count');
        $this->addSql('ALTER TABLE playlist_generation_jobs DROP resumed_from_job_id');

        $this->addSql('DROP TABLE user_track_preferences');
    }
}
