<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Streaming port and account linking (docs/specs/2026-08-22-streaming-port-and-account-linking.md,
 * D-77, D-78): `streaming_accounts` — one row per (user, provider) link. `access_token`/
 * `refresh_token` are `text` columns holding the `encrypted_string` Doctrine type's ciphertext
 * envelope (App\Doctrine\Type\EncryptedStringType), never plaintext (AC-6.1, AC-6.2).
 */
final class Version20260822140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Streaming port and account linking: streaming_accounts (D-77, D-78).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE streaming_accounts (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                provider VARCHAR(32) NOT NULL,
                access_token TEXT DEFAULT NULL,
                refresh_token TEXT DEFAULT NULL,
                expires_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL,
                scopes JSON NOT NULL,
                provider_account_id VARCHAR(128) NOT NULL,
                provider_display_name VARCHAR(200) DEFAULT NULL,
                status VARCHAR(20) NOT NULL,
                linked_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL,
                PRIMARY KEY(id)
            )
            SQL);
        $this->addSql('CREATE UNIQUE INDEX uniq_streaming_accounts_user_provider ON streaming_accounts (user_id, provider)');
        // AC-2.2's operator-visibility index (docs/architecture.md §10): cheap because it excludes
        // the common case (connected).
        $this->addSql("CREATE INDEX idx_streaming_accounts_status ON streaming_accounts (status) WHERE status <> 'connected'");
        $this->addSql('ALTER TABLE streaming_accounts ADD CONSTRAINT fk_streaming_accounts_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE streaming_accounts');
    }
}
