<?php

declare(strict_types=1);

namespace App\Tests\Functional\ConcertReview;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Schema\Schema;
use Psr\Log\NullLogger;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

// Migration classes are deliberately NOT autoloaded (composer.json's own comment on
// `migrations_paths`/PSR-4: "migrations classes should NOT be autoloaded") — require the one file
// this test drives directly, exactly the way `bin/console doctrine:migrations:migrate` itself
// discovers migration classes by path rather than by namespace autoloading.
require_once \dirname(__DIR__, 3).'/migrations/Version20260826140000.php';

/**
 * AC-8.1-AC-8.8, R-1: `DoctrineMigrations\Version20260826140000` (docs/specs/2026-08-26-notes-and-reviews.md) copies
 * every non-blank `Concert.note` into a `ConcertReview`, verifies the count, and only then drops
 * the column — all against a REAL Postgres, because text round-tripping (a ZWJ emoji, in
 * particular) is exactly what a mock would not catch.
 *
 * Runs the migration's `up()`/`down()` against a throwaway schema (`search_path` scoped to it, not
 * `public`) seeded with the minimal `users`/`concerts`/`songs` shape the migration's SQL touches —
 * never against the shared suite-wide `public` schema every other functional test uses. This avoids
 * migrating the WHOLE chain back and forth (this repo's tests share one persistent database with no
 * per-test rollback, so replaying every migration's down()/up() here would risk clobbering
 * migration-seeded rows other test classes depend on) while still executing this migration's own
 * real SQL against a real server.
 */
final class ConcertReviewMigrationTest extends KernelTestCase
{
    private Connection $connection;
    private string $schema;

    protected function setUp(): void
    {
        self::bootKernel();
        $this->connection = static::getContainer()->get('doctrine.dbal.default_connection');
        $this->schema = 'concert_review_migration_test_'.bin2hex(random_bytes(6));

        $this->connection->executeStatement(\sprintf('CREATE SCHEMA %s', $this->schema));
        $this->connection->executeStatement(\sprintf('SET search_path TO %s', $this->schema));

        $this->connection->executeStatement('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)');
        $this->connection->executeStatement(<<<'SQL'
            CREATE TABLE concerts (
                id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                owner_id INT NOT NULL REFERENCES users (id),
                note TEXT DEFAULT NULL,
                updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL
            )
            SQL);
        $this->connection->executeStatement('CREATE TABLE songs (id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)');

        $this->connection->executeStatement('INSERT INTO users DEFAULT VALUES');
    }

    protected function tearDown(): void
    {
        $this->connection->executeStatement('SET search_path TO public');
        $this->connection->executeStatement(\sprintf('DROP SCHEMA IF EXISTS %s CASCADE', $this->schema));

        parent::tearDown();
    }

    /** @return array<string, int> label => concerts.id, for the five AC-8.6 seeded shapes */
    private function seedConcerts(): array
    {
        $now = '2024-03-15 10:00:00+00';
        $family = "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}\u{200D}\u{1F466}"; // 👨‍👩‍👧‍👦, one ZWJ sequence

        $ids = [];
        $ids['plain'] = $this->insertConcert('Bought tickets the day they went on sale.', $now);
        $ids['zwj_emoji'] = $this->insertConcert('What a night '.$family.' unforgettable.', $now);
        $ids['old_limit'] = $this->insertConcert(str_repeat('a', 2000), $now);
        $ids['whitespace_only'] = $this->insertConcert('   ', $now);
        $ids['null'] = $this->insertConcert(null, $now);

        return $ids;
    }

    private function insertConcert(?string $note, string $updatedAt): int
    {
        $this->connection->executeStatement(
            'INSERT INTO concerts (owner_id, note, updated_at) VALUES (1, :note, :updated_at)',
            ['note' => $note, 'updated_at' => $updatedAt],
        );

        return self::toInt($this->connection->fetchOne('SELECT MAX(id) FROM concerts'));
    }

    private static function toInt(mixed $value): int
    {
        return \is_numeric($value) ? (int) $value : 0;
    }

    /** Executes a migration's queued SQL against `$this->connection` (see class docblock). */
    private function runUp(\DoctrineMigrations\Version20260826140000 $migration): void
    {
        $schema = new Schema();
        $migration->up($schema);
        $this->executeQueuedSql($migration->getSql());
    }

    private function runDown(\DoctrineMigrations\Version20260826140000 $migration): void
    {
        $schema = new Schema();
        $migration->down($schema);
        $this->executeQueuedSql($migration->getSql());
    }

    /** @param array<\Doctrine\Migrations\Query\Query> $queries */
    private function executeQueuedSql(array $queries): void
    {
        foreach ($queries as $query) {
            // Neither up() nor down() above declares bound parameter types (see the migration
            // itself — every addSql() call is a plain string), so this migration's own queue never
            // populates Query::getTypes() with anything DBAL's executeStatement() would reject.
            $this->connection->executeStatement($query->getStatement(), $query->getParameters());
        }
    }

    public function testMigrationMovesExactlyTheNonBlankNotesAndDropsTheColumn(): void
    {
        $ids = $this->seedConcerts();

        $migration = new \DoctrineMigrations\Version20260826140000($this->connection, new NullLogger());
        $this->runUp($migration);

        // AC-8.3: null and whitespace-only notes produce no review.
        $reviewCount = self::toInt($this->connection->fetchOne('SELECT COUNT(*) FROM concert_reviews'));
        self::assertSame(3, $reviewCount, 'Exactly the plain, ZWJ-emoji and 2000-char notes should migrate.');

        $rows = $this->connection->fetchAllAssociativeIndexed(
            'SELECT concert_id, notes, rating, source_note_migrated_at, created_at, updated_at FROM concert_reviews',
        );

        self::assertArrayHasKey($ids['plain'], $rows);
        self::assertSame('Bought tickets the day they went on sale.', $rows[$ids['plain']]['notes']);

        self::assertArrayHasKey($ids['zwj_emoji'], $rows);
        $family = "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}\u{200D}\u{1F466}";
        self::assertSame('What a night '.$family.' unforgettable.', $rows[$ids['zwj_emoji']]['notes']);
        self::assertSame(1, grapheme_strlen($family));

        self::assertArrayHasKey($ids['old_limit'], $rows);
        self::assertSame(str_repeat('a', 2000), $rows[$ids['old_limit']]['notes']);

        self::assertArrayNotHasKey($ids['whitespace_only'], $rows);
        self::assertArrayNotHasKey($ids['null'], $rows);

        // AC-8.1: every migrated row is rating-NULL, provenance-stamped.
        foreach ($rows as $row) {
            self::assertNull($row['rating']);
            self::assertNotNull($row['source_note_migrated_at']);
            self::assertSame('2024-03-15 10:00:00+00', $row['created_at']);
            self::assertSame('2024-03-15 10:00:00+00', $row['updated_at']);
        }

        // AC-8.5: concerts.note is gone.
        $noteColumn = $this->connection->fetchOne(
            "SELECT column_name FROM information_schema.columns WHERE table_schema = :schema AND table_name = 'concerts' AND column_name = 'note'",
            ['schema' => $this->schema],
        );
        self::assertFalse($noteColumn);
    }

    public function testDownReAddsTheColumnAndRestoresExactlyTheMigratedRows(): void
    {
        $ids = $this->seedConcerts();

        // Two separate instances — `Doctrine\Migrations\AbstractMigration::addSql()` accumulates
        // into one internal queue for the LIFETIME of the object, so reusing the same instance for
        // both up() and down() would replay up()'s already-applied CREATE TABLE alongside down()'s
        // own statements. `bin/console doctrine:migrations:migrate` never reuses an instance across
        // directions either — a fresh one is exactly what real usage looks like.
        $this->runUp(new \DoctrineMigrations\Version20260826140000($this->connection, new NullLogger()));
        $this->runDown(new \DoctrineMigrations\Version20260826140000($this->connection, new NullLogger()));

        $noteColumn = $this->connection->fetchOne(
            "SELECT column_name FROM information_schema.columns WHERE table_schema = :schema AND table_name = 'concerts' AND column_name = 'note'",
            ['schema' => $this->schema],
        );
        self::assertSame('note', $noteColumn);

        $notes = $this->connection->fetchAllKeyValue('SELECT id, note FROM concerts');
        self::assertSame('Bought tickets the day they went on sale.', $notes[$ids['plain']]);
        $family = "\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}\u{200D}\u{1F466}";
        self::assertSame('What a night '.$family.' unforgettable.', $notes[$ids['zwj_emoji']]);
        self::assertSame(str_repeat('a', 2000), $notes[$ids['old_limit']]);

        // The two rows the migration never touched must NOT be resurrected with some other value.
        self::assertNull($notes[$ids['whitespace_only']]);
        self::assertNull($notes[$ids['null']]);

        $tableExists = $this->connection->fetchOne(
            'SELECT to_regclass(:qualified)',
            ['qualified' => $this->schema.'.concert_reviews'],
        );
        self::assertNull($tableExists, 'to_regclass() returns NULL, not false, for a relation that does not exist.');
    }

    /**
     * AC-8.8: a re-run is a no-op. In practice this is guaranteed structurally, in two independent
     * ways, neither of which this migration's own SQL needs to implement: (1) Doctrine Migrations
     * itself tracks applied versions in `doctrine_migration_versions` and never re-executes one
     * already recorded; (2) even a manual, out-of-band repeat of just the `INSERT ... SELECT`
     * portion for a concert already migrated would collide with
     * `uniq_concert_reviews_owner_concert` — proven directly by
     * `App\Tests\Functional\ConcertReview\ConcertReviewUniqueConstraintTest`. This test asserts the
     * second half: a duplicate insert for an already-migrated (owner, concert) pair is rejected.
     */
    public function testAttemptingToMigrateTheSamePairTwiceViolatesTheUniqueIndex(): void
    {
        $ids = $this->seedConcerts();

        $migration = new \DoctrineMigrations\Version20260826140000($this->connection, new NullLogger());
        $this->runUp($migration);

        $this->expectException(\Doctrine\DBAL\Exception\UniqueConstraintViolationException::class);
        $this->connection->executeStatement(
            'INSERT INTO concert_reviews (owner_id, concert_id, notes, rating, created_at, updated_at, source_note_migrated_at) VALUES (1, :concert, :notes, NULL, NOW(), NOW(), NOW())',
            ['concert' => $ids['plain'], 'notes' => 'A second attempt at the same pair.'],
        );
    }
}
