<?php

declare(strict_types=1);

namespace App\Service\Streaming;

use App\Service\Streaming\Model\PlaylistDraft;
use App\Service\Streaming\Model\ProviderPlaylist;
use App\Service\Streaming\Model\ProviderTokens;
use App\Service\Streaming\Model\SongQuery;
use App\Service\Streaming\Model\TrackCandidate;

/**
 * The single most important abstraction in the codebase (`docs/architecture.md` §4). Every provider
 * is reached through this and only this — `CLAUDE.md`: "the streaming port is the only way to reach
 * a provider". No provider-specific symbol may appear in any consumer of this interface; a static
 * architecture test enforces that structurally for the first real adapter (D-82).
 *
 * **Frozen at exactly these nine methods (D-71).** A provider that needs more does not get a wider
 * interface — the value of this port is entirely in its narrowness. If a future provider genuinely
 * cannot express something through these methods, the answer is a capability value object returned
 * by the port, or the feature does not exist for that provider, never an eleventh method.
 *
 * Every method that can fail with a provider-side error throws only the taxonomy in
 * `Exception/` (US-10, D-73) — never a raw HTTP status, never a provider-shaped exception. An
 * unclassified adapter failure becomes `Exception\ProviderUnavailableException` (AC-10.5), never a
 * raw exception escaping the adapter.
 *
 * **Deviation from the literal `docs/architecture.md` §4 sketch, recorded here rather than left
 * implicit**: `authorizationUrl()` and `exchangeCode()` each gained one optional, nullable, generic
 * parameter (`$codeChallenge`/`$codeVerifier`) that the sketch's two-argument signatures do not
 * show. PKCE (AC-1.2, D-74) requires a challenge to reach the provider's authorization URL and the
 * matching verifier to reach the token exchange, and the frozen interface otherwise has no channel
 * to carry either — OAuth2 PKCE is a provider-agnostic standard, not a provider-specific concern,
 * so widening these two parameters (not adding a method — the method count is still nine, D-71) was
 * judged the more honest fix than deriving/caching a verifier statelessly inside an adapter
 * instance, which would be unsafe under a persistent worker (this app runs FrankenPHP). Both
 * parameters default to null so a provider without PKCE support is unaffected.
 */
interface StreamingProviderInterface
{
    /** The provider's stable key, e.g. `'spotify'` — never a class name (D-72). */
    public function key(): string;

    // --- OAuth ---------------------------------------------------------------------------------

    /**
     * Builds the provider's authorization URL for this `$state` and `$redirectUri` (AC-1.1). The
     * calling code never assembles a provider URL itself — every provider-specific query parameter
     * (client id, scopes, response type) is the adapter's business. `$codeChallenge` (PKCE S256,
     * AC-1.2) is generated by the caller and passed through; null means the provider does not use
     * PKCE.
     */
    public function authorizationUrl(string $state, string $redirectUri, ?string $codeChallenge = null): string;

    /**
     * Exchanges an authorization `$code` for a token pair (AC-1.4), fetching the provider's account
     * identity as part of the same call and populating it on the returned `ProviderTokens`.
     * `$codeVerifier` is the PKCE verifier the caller generated and stored server-side (AC-1.2); null
     * for a provider that does not use PKCE.
     */
    public function exchangeCode(string $code, string $redirectUri, ?string $codeVerifier = null): ProviderTokens;

    /**
     * Refreshes an expired/expiring token pair. Throws `Exception\TokenExpiredException` for an
     * unrecoverable grant failure (D-80) — never returns a partial or null result.
     */
    public function refreshToken(ProviderTokens $tokens): ProviderTokens;

    // --- Catalog ---------------------------------------------------------------------------------

    /**
     * @return list<TrackCandidate> ordered by descending confidence (AC-11.1). Empty array for no
     *                               results — never an exception (AC-11.6, CLAUDE.md: generation
     *                               degrades, it does not fail).
     */
    public function searchTrack(SongQuery $query, ProviderTokens $tokens): array;

    // --- Playlists ---------------------------------------------------------------------------------

    /** Creates a private playlist (D-87) and returns its provider identity (AC-11.4). */
    public function createPlaylist(PlaylistDraft $draft, ProviderTokens $tokens): ProviderPlaylist;

    /**
     * Adds track ids to an existing playlist. The caller passes the full list and knows nothing
     * about the provider's batch limit — chunking happens inside the adapter (AC-11.5).
     *
     * @param list<string> $trackIds
     */
    public function addTracks(string $playlistId, array $trackIds, ProviderTokens $tokens): void;

    // --- Playback surface (docs/architecture.md §7) -------------------------------------------------

    /** An embeddable player URL for this playlist, or null if the provider has none. */
    public function playlistEmbedUrl(string $playlistId): ?string;

    /** A URL/deep-link that hands off playback to the provider's own app. */
    public function playlistDeepLink(string $playlistId): string;
}
